name: myfinance
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  uuid: ^4.4.0
  cloud_firestore: 4.17.3
  intl: ^0.17.0
  http: ^1.2.1
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.13.0
  fl_chart: ^0.68.0
  animated_line_chart: ^0.0.3
  shared_preferences: ^2.0.9
  flutter_slidable:
  draggable_menu: ^4.4.1
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2
  build_runner: ^2.4.10

flutter_icons:
  android: true
  ios: true
  image_path: "lib/Assets/myfinance.jpg"

flutter:
  uses-material-design: true

  assets:
    - lib/Assets/Sfondo.webp
    - lib/Assets/myfinance.jpg
