// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvwI2wEQotwWyuxJdwAVhx85tLF7wo8pg',
    appId: '1:1056931152928:web:64e3aa0a33495d2e7d2845',
    messagingSenderId: '1056931152928',
    projectId: 'myfinance-afb2a',
    authDomain: 'myfinance-afb2a.firebaseapp.com',
    storageBucket: 'myfinance-afb2a.appspot.com',
    measurementId: 'G-B0Q2SRS3Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1x3b5C0lW0dWMUHx6LW0FcGO5eGEYJkE',
    appId: '1:1056931152928:android:c90494c43d227fde7d2845',
    messagingSenderId: '1056931152928',
    projectId: 'myfinance-afb2a',
    storageBucket: 'myfinance-afb2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj1CWDNiookmowM2e0wzy5zM6so3QX6ZA',
    appId: '1:1056931152928:ios:aa5ef5c5a9efc6297d2845',
    messagingSenderId: '1056931152928',
    projectId: 'myfinance-afb2a',
    storageBucket: 'myfinance-afb2a.appspot.com',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj1CWDNiookmowM2e0wzy5zM6so3QX6ZA',
    appId: '1:1056931152928:ios:aa5ef5c5a9efc6297d2845',
    messagingSenderId: '1056931152928',
    projectId: 'myfinance-afb2a',
    storageBucket: 'myfinance-afb2a.appspot.com',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvwI2wEQotwWyuxJdwAVhx85tLF7wo8pg',
    appId: '1:1056931152928:web:3bfe28d0bdd2c66c7d2845',
    messagingSenderId: '1056931152928',
    projectId: 'myfinance-afb2a',
    authDomain: 'myfinance-afb2a.firebaseapp.com',
    storageBucket: 'myfinance-afb2a.appspot.com',
    measurementId: 'G-GLYN12QEWD',
  );
}
